### ISSUE TITLE
XML Parsing error when opening in v18.0

### ISSUE THREAD

**Issue by EWTHeckman** [ThomasMaul/UserMode_Component#1]
When opening this 4D Project with version 18.0 (on Windows 10) I'm getting the following error:

![image](https://user-images.githubusercontent.com/43447434/76467499-22fb8100-63c0-11ea-8561-dbcc90ea874f.png)

This happens whether opening the project directly or when built as a component and installed in a host database. I have not been able to locate the XML file that is causing the problem.

**Comment by ThomasMaul** [comment]
The previous version was an export made with 4D v17 R3, not a useable project. It required still to use the 4DB format to modify the source.
I just uploaded a "real" project, directly reusable. Please check Readme - history for details. 
Thanks for the report.

**Comment by EWTHeckman** [comment]
Hi Thomas,

I'm still getting the same error with the update.

I'm not sure what you mean by requiring the 4DB format to modify the source. My understanding (admittedly sketchy, so far) of Projects is that it is a one way conversion. You can go from .4DB to Project, but not the other direction.

**Comment by ThomasMaul** [comment]
sorry again. There was an error in the English xliff file, which did not happened for me (on a German system). I correcte dthat.
Project are one way conversion, yes, correct. 
I created this repository using 4D v17 R3, which was not able to convert to project mode yet, it was only able to export most of the files. So it was useable to track changes, but not to directly use the file. Or in other words: I coded with 4DB and exported every time I wanted to commit changes to git, using git only as version history, not as version control.
Sorry again, I'm currently quite busy with our events, I did not tested with an US system, I just corrected the xml error, run a xml validate and commited the change.

**Comment by EWTHeckman** [comment]
Thank you for your quick response on this, Thomas. Sorry to be bugging you.

The fresh commit was _still_ throwing the same error. But your comments helped me track it down. The most recent commit did not include the updated en.xlf file. By comparing it to the German file I was able to correct it manually to remove the extra /group line.
